### ISSUE TITLE
Core dumped at startup

### ISSUE THREAD

**Issue by luiz-rocha** [lanoxx/tilda#259]
I'm getting this error when running tilda, have some advise?
Thank you anyway.

(tilda:31622): Vte-WARNING **: (vtegtk.cc:1739):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
[1]    31622 segmentation fault (core dumped)  tilda

$ tilda -v
Tilda 1.4~alpha
I've installed with dnf but didn't work, so I compiled and have the same problem.

Reading symbols from tilda...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/tilda 
Missing separate debuginfos, use: dnf debuginfo-install tilda-1.3.3-1.fc24.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Detaching after fork from child process 31561.
[New Thread 0x7fffe399e700 (LWP 31562)]
[New Thread 0x7fffe319d700 (LWP 31563)]
[New Thread 0x7fffe278f700 (LWP 31564)]
[New Thread 0x7fffe1b26700 (LWP 31566)]
[New Thread 0x7fffe1325700 (LWP 31567)]
[New Thread 0x7fffe0b24700 (LWP 31568)]
[New Thread 0x7fffd3fff700 (LWP 31569)]
[New Thread 0x7fffd37fe700 (LWP 31570)]
[New Thread 0x7fffd2822700 (LWP 31571)]

(tilda:31557): Vte-WARNING **: (vtegtk.cc:1739):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
Detaching after fork from child process 31572.

Thread 1 "tilda" received signal SIGSEGV, Segmentation fault.
0x00007ffff5d6198c in XGetModifierMapping () from /lib64/libX11.so.6
(gdb) backtrace
#0  0x00007ffff5d6198c in XGetModifierMapping () at /lib64/libX11.so.6
#1  0x000000000040a07c in reload_modmap ()
#2  0x000000000040a39c in egg_keymap_get_modmap ()
#3  0x0000000000409eeb in egg_keymap_resolve_virtual_modifiers ()
#4  0x0000000000411629 in lookup_ignorable_modifiers ()
#5  0x0000000000411ac2 in tomboy_keybinder_init ()
#6  0x000000000040c652 in main ()

**Comment by luiz-rocha** [comment]
Ok found it, tilda is incompatible with Fedora 24 Wayland.
