### ISSUE TITLE
slide animation crashes

### ISSUE THREAD

**Issue by gijsbers** [lanoxx/tilda#318]
`slide_sleep_usec = 1000`
can easily crash tilda when keeping F1 pressed too long:
```
#0  0x00007ff7a1908713 in g_logv () at /usr/lib64/libglib-2.0.so.0
#1  0x00007ff7a1908882 in g_log () at /usr/lib64/libglib-2.0.so.0
#2  0x000000000041674f in xerror_handler (d=<optimized out>, e=<optimized out>)
    at src/xerror.c:38
#3  0x00007ff7a115f1fb in _XError () at /usr/lib64/libX11.so.6
#4  0x00007ff7a115c2d7 in  () at /usr/lib64/libX11.so.6
#5  0x00007ff7a115c385 in  () at /usr/lib64/libX11.so.6
#6  0x00007ff7a115cdcd in _XReadEvents () at /usr/lib64/libX11.so.6
#7  0x00007ff7a114eb20 in XPeekEvent () at /usr/lib64/libX11.so.6
#8  0x000000000040ecdb in focus_out_event_cb (widget=<optimized out>, event=<optimized out>, data=0x7ffdd758f990) at src/tilda_window.c:594
#9  0x00007ff7a2ae68a5 in  () at /usr/lib64/libgtk-3.so.0
#10 0x00007ff7a1bd6908 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#11 0x00007ff7a1be830d in  () at /usr/lib64/libgobject-2.0.so.0
#12 0x00007ff7a1beff78 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#13 0x00007ff7a1bf0592 in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#14 0x00007ff7a2c1ef1c in  () at /usr/lib64/libgtk-3.so.0
#15 0x00007ff7a2ae58fa in gtk_main_do_event () at /usr/lib64/libgtk-3.so.0
#16 0x00007ff7a2638a85 in  () at /usr/lib64/libgdk-3.so.0
#17 0x00007ff7a2664cf2 in  () at /usr/lib64/libgdk-3.so.0
#18 0x00007ff7a1902134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ff7a1902388 in  () at /usr/lib64/libglib-2.0.so.0
#20 0x00007ff7a190264a in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#21 0x00007ff7a2ae4c85 in gtk_main () at /usr/lib64/libgtk-3.so.0
#22 0x000000000040bd82 in main (argc=<optimized out>, argv=<optimized out>)
    at src/tilda.c:891
```

**Comment by lanoxx** [comment]
Should be fixed by 3d8fad0219498dc05d408bf0c6df6ac3494bafe6 which improves the way tilda behaves when users keep the pull hotkey pressed for too long.
