### ISSUE TITLE
segmentation fault on fedora 28

### ISSUE THREAD

**Issue by Kidlike** [lanoxx/tilda#359]
I just upgraded from fedora 27 to 28 and tilda crashes on startup.

This is the backtrace from gdb:

```
Thread 1 "tilda" received signal SIGSEGV, Segmentation fault.
#0  0x00007ffff5cdab55 in _XReply () from /lib64/libX11.so.6
#1  0x00007ffff5cc9240 in XGetModifierMapping () from /lib64/libX11.so.6
#2  0x000055555555f73a in reload_modmap (modmap=0x555555f66560, keymap=0x5555557e4400) at src/eggaccelerators.c:173
#3  egg_keymap_get_modmap (keymap=0x5555557e4400) at src/eggaccelerators.c:173
#4  0x000055555555f9a4 in egg_keymap_resolve_virtual_modifiers (keymap=0x5555557e4400, virtual_mods=EGG_VIRTUAL_LOCK_MASK, concrete_mods=0x55555577aec4 <caps_lock_mask>) at src/eggaccelerators.c:56
#5  0x000055555556587a in lookup_ignorable_modifiers (keymap=0x5555557e4400) at src/tomboykeybinder.c:88
#6  0x0000555555565e42 in tomboy_keybinder_init () at src/tomboykeybinder.c:319
#7  0x000055555555e71d in main (argc=<optimized out>, argv=<optimized out>) at src/tilda.c:842
```

**Comment by Kidlike** [comment]
nevermind... after the update it lost my setting to login using Xorg instead of Wayland :)
