### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by joekendal** [lanoxx/tilda#363]
```shell
$ tilda

(tilda:13076): Vte-WARNING **: 11:52:47.352: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
tilda: ../../src/xcb_io.c:568: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
Aborted (core dumped)
```
```shell
(gdb) run
Starting program: /usr/bin/tilda 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb589700 (LWP 13156)]
[New Thread 0x7fffead88700 (LWP 13157)]
[New Thread 0x7fffea146700 (LWP 13158)]
[New Thread 0x7fffe9329700 (LWP 13159)]
[New Thread 0x7fffe8b28700 (LWP 13160)]
[New Thread 0x7fffdbfff700 (LWP 13163)]
[New Thread 0x7fffdb7fe700 (LWP 13164)]
[New Thread 0x7fffdaffd700 (LWP 13165)]

(tilda:13150): Vte-WARNING **: 11:53:52.617: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)

Thread 1 "tilda" received signal SIGSEGV, Segmentation fault.
0x00007ffff5cf3982 in _XReply ()
   from /usr/lib/x86_64-linux-gnu/libX11.so.6
(gdb) backtrace
#0  0x00007ffff5cf3982 in _XReply ()
   from /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x00007ffff5ce245f in XGetModifierMapping ()
   from /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x000055555555f81a in ?? ()
#3  0x000055555555fa60 in ?? ()
#4  0x000055555556585a in ?? ()
#5  0x0000555555565e2e in ?? ()
#6  0x000055555555e845 in ?? ()
#7  0x00007ffff56c7b97 in __libc_start_main (main=0x55555555de60, 
    argc=1, argv=0x7fffffffe068, init=<optimised out>, 
    fini=<optimised out>, rtld_fini=<optimised out>, 
    stack_end=0x7fffffffe058) at ../csu/libc-start.c:310
#8  0x000055555555f03a in ?? ()
(gdb) 

```

**Comment by lanoxx** [comment]
From the posted stacktrace its impossible to identify the problem. If you can reproduce the problem with more debug symbols then please reopen the bug. Pleaese also confirm if this problem is still occuring in the latest version.
